version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my-network

  node-app:
    build: 
      context: ./master_api
    ports:
      - "5100:5100"
    depends_on:
      - redis
      - rabbitmq
    networks:
      - my-network

  cover-letter-pdf-generation:
    build: 
      context: ./Microservices/CoverLetterPDFGeneration
    depends_on:
      - rabbitmq
    networks:
      - my-network

  resume-and-cover_letter-creation:
    build: 
      context: ./Microservices/GeminiProcessing
    depends_on:
      - rabbitmq
    networks:
      - my-network

  interview-processing:
    build: 
      context: ./Microservices/InterviewProcessing
    container_name: interview-processing
    depends_on:
      - rabbitmq
    networks:
      - my-network



networks:
  my-network:
