version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my-network

  node-app:
    build: 
      context: ./master_api
    ports:
      - "5100:5100"
    depends_on:
      - redis
      - rabbitmq
    networks:
      - my-network

  microservice_resume_and_coverletter:
    build: 
      context: ./Microservices/GeminiProcessing
    depends_on:
      - rabbitmq
    networks:
      - my-network

  microservice_interview_processing:
    build: 
      context: ./Microservices/InterviewProcessing
    depends_on:
      - rabbitmq
    networks:
      - my-network

  microservice_cover_letter_pdf_generation:
    build: 
      context: ./Microservices/CoverLetterPDFGeneration
    depends_on:
      - rabbitmq
    networks:
      - my-network

networks:
  my-network:

volumes:
  ollama:
