version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my-network

  node-app:
    build: 
      context: ./master_api
    ports:
      - "5100:5100"
    depends_on:
      - redis
      - rabbitmq
    networks:
      - my-network

  microservice_resume:
    build: 
      context: ./Microservices/ResumeProcessing
    depends_on:
      - rabbitmq
    networks:
      - my-network

networks:
  my-network:
